# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  aws_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  aws_bucket: ironyard-restaurant-dbern
  secret_key_base: 19dcf12ab0978c3adbe7417c14ad19041e684a87e41bac5f3a1a6a80019d4e6ce6d951e74039ab8b66ecf53ed27e63e19358b722226c440a00fc24d07b47fd6f

test:
  secret_key_base: 454c75cdfb4b0c8dc8c68aef0b9b66082bece7299a92ad677ffcf4987eede026395eafd2f977ab7582f6071840f1619969295d5128d59cb76dd9b77172af0dc3
  aws_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  aws_bucket: ironyard-restaurant-dbern

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  aws_bucket: ironyard-restaurant-dbern

